{% set name = "jupyter-pluto-proxy" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter-pluto-proxy-{{ version }}.tar.gz
  sha256: ef2ed5b71dcd0ea3cceb6b992ba22483a3b9a56a1705add493597b993233c162

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jupyter-server-proxy >=1.5.0

test:
  imports:
    - jupyter_pluto_proxy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yuvipanda/jupyter-pluto-proxy
  summary: Run Pluto.jl in JupyterHub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yuvipanda
